---
- hosts: 172.31.20.147
  become: yes
  tasks:
  - name: I want to install linux commands
    command: hostname -f
    register: myresultvar
  
  - name: debug myresultvar
    debug:
     msg: "{{myresultvar}}"

  - name: I want to install git
    apt:
     name: git
     state: present
    when: myresultvar.stderr==""
  
  - name: I want to install tree
    apt:
     name: tree
     state: present
    when: myresultvar.stderr!=""