---
- hosts: mywebservers
  become: yes
  gather_facts: yes
  tasks:
  - name: I want to install webserver on ubuntu
    apt:
      name: {{myubuntuwebpack}}
      state: present
    when: ansible_os_family=="Debian"

  - name: start webserver on ubuntu
    service:
      name: {{myubuntuwebpack}}
      state: started
    when: ansible_os_family=="Debian"

  - name: I want to install webserver on RedHat
    yum:
      name: {{myredhatwebpack}}
      state: present
    when: ansible_os_family=="RedHat"

  - name: start webserver on RedHat
    service:
      name: {{myredhatwebpack}}
      state: started
    when: ansible_os_family=="RedHat" 
